import string


SMALLEST_PRECEDENCE = 1
ASSIGNMENT_PRECEDENCE = 1
ADDITION_PRECEDENCE = 2
SUBTRACTION_PRECEDENCE = 2
MULTIPLICATION_PRECEDENCE = 3
DIVISION_PRECEDENCE = 3
MODULO_PRECEDENCE = 3
BIGGEST_PRECEDENCE = 3

IDENTIFIER_BEGIN_CHARACTERS = string.ascii_letters + '_'
IDENTIFIER_CHARACTERS = IDENTIFIER_BEGIN_CHARACTERS + string.digits
DECIMAL_NUMBER_CHARACTERS = string.digits

