name: Black

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Black
        uses: psf/black@stable
        with:
          options: "--line-length 79 --target-version py310"
          src: "./projector"
          
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
